
server:
  port: 8002

spring:
  application:
    name: payment-provider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

  instance:
    instance-id: provider8002

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.yangzl.springcloud.entities