server:
  port: 8001

spring:
  application:
    name: payment-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:7001/eureka,http://localhost:7002/eureka

  instance:
    instance-id: provider8001-hystrix
