
server:
  port: 80

spring:
  application:
    name: consumer


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

# 设置客户端调用超时时间
ribbon:
  ReadTimeout: 3000

# spring日志配置，默认以console，debug级别打印日志
logging:
  level:
    com.yangzl.spirngcloud.service.**: debug
