server:
  port: 8006

spring:
  application:
    name: payment-provider

  # consul注册中心配置
  # consul 启动 consul agent dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}